# https://taskfile.dev

version: '3'

tasks:
  # main tasks
  default:
    deps: [run]

  run:
    desc: Start the php server
    silent: true
    cmds:
      - task: install
      - task: .env
      - task: build
      - php artisan serve

  # Generate files tasks
  .env:
    desc: Creates the .env file if does not exist
    silent: true
    deps: [vendor]
    status:
      - test -f .env # only runs if .env does not exist
    cmds:
      - cp .env.example .env
      - php artisan key:generate --ansi

  ide-helper:
    desc: Creates the _ide_helper.php and _ide_helper_models.php files
    silent: true
    deps: [vendor]
    cmds:
      - php artisan ide-helper:generate
      - php artisan ide-helper:models -N

  # Build tasks
  build:
    desc: Build assets with vite
    deps: [node_modules]
    silent: true
    sources:
      - resources/js/*.js
      - resources/css/*.css
    generates:
      - public/build/manifest.json
    cmds:
      - npm run build

  # Install deps tasks
  install:
    desc: Install all dependencies
    silent: true
    cmds:
      - task: node_modules
      - task: vendor

  vendor:
    desc: Install PHP dependencies
    silent: true
    sources:
      - ./composer.json
      - ./composer.lock
    generates:
      - ./vendor/autoload.php
    cmds:
      - rm -rf vendor
      - composer install

  node_modules:
    desc: Install NPM dependencies
    silent: true
    sources:
      - ./package.json
      - ./package-lock.json
    generates:
      - ./node_modules/.package-lock.json
    cmds:
      - rm -rf node_modules
      - npm install

  # Other tasks
  clear:
    desc: Remove node_modules, vendor and .task directories and "ide_helper" files
    silent: true
    cmds:
      - rm -rf node_modules vendor _ide_helper*.php
