# https://taskfile.dev

version: '3'

tasks:
  # main tasks
  default:
    deps: [run]

  run:
    desc: Start the php server
    silent: true
    cmds:
      - task: install
      - task: build
      - task: storage-link
      - php artisan serve

  # Generate files tasks
  .env:
    desc: Creates the .env file if does not exist
    silent: true
    status:
      - test -f .env # only runs if .env does not exist
    cmds:
      - cp .env.example .env

  ide-helper:
    desc: Creates the _ide_helper.php and _ide_helper_models.php files
    deps: [vendor]
    silent: true
    cmds:
      - php artisan ide-helper:generate
      - php artisan ide-helper:models -N

  storage-link:
    desc: Creates symlink "public/storage" -> "storage/app/public"
    deps: [vendor]
    silent: true
    status:
      - test -h public/storage # only runs if "public/storage" does not exist
    cmds:
      - php artisan storage:link

  # Build tasks
  build:
    desc: Build assets with vite
    deps: [node_modules]
    silent: true
    sources:
      - resources/js/*.js
      - resources/css/*.css
      - node_modules/.package-lock.json # Rebuild if deps change
    generates:
      - public/build/manifest.json
    cmds:
      - npm run build

  # Install deps tasks
  install:
    desc: Install all dependencies
    silent: true
    cmds:
      - task: node_modules
      - task: vendor

  vendor:
    desc: Install PHP dependencies
    deps: [.env]
    silent: true
    sources:
      - ./composer.json
      - ./composer.lock
    generates:
      - ./vendor/autoload.php
    cmds:
      - rm -rf vendor
      - composer install

  node_modules:
    desc: Install NPM dependencies
    silent: true
    sources:
      - ./package.json
      - ./package-lock.json
    generates:
      - ./node_modules/.package-lock.json
    cmds:
      - rm -rf node_modules
      - npm install

  # Other tasks
  clear:
    desc: Removes the node_modules, vendor and public/build directories, also the "ide_helper" files
    silent: true
    cmds:
      - rm -rf node_modules
      - rm -rf vendor
      - rm -rf _ide_helper*.php
      - rm -rf public/build
